
SELECT * FROM MN_PERSON mp 						--68
SELECT * FROM MN_DES_PERSON  mdp  		--3279668
SELECT * FROM MN_DES_ADDRESS mda 		--6497560
SELECT * FROM MN_DES_ADDRESS_HIS mdah 	--1974012
SELECT count(*) FROM MN_DES_DEFORMED_ASSESS mdda 	--762366
SELECT * FROM MN_DES_DEFORMED mdd 				--3530744
SELECT * FROM BS_DEFORM bd 	 					--19
SELECT * FROM BS_ADDRESS ba 					--9
SELECT * FROM BS_SEX bs 						--2

SELECT * FROM BS_SUBDISTRICT bs 				--8549
SELECT * FROM BS_DISTRICT bd2 					--1014
SELECT * FROM BS_PROVINCE bp 					--77
SELECT * FROM "OPP$_DBA".BS_REGION br 						--5

SELECT * FROM ALL_TAB_COLS 
WHERE table_name = 'MN_DES_PERSON'

DROP dep_join_view;

--SELECT BY region
SELECT br.REGION_CODE, 
	br.REGION_NAME_THAI,
	COUNT(br.REGION_CODE) AS TOTAL,
	SUM(CASE mdp.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
	SUM(CASE mdp.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_REGION br ON bp.REGION_CODE = br.REGION_CODE 
WHERE mda.ADDRESS_CODE = '02'
GROUP BY br.REGION_CODE, br.REGION_NAME_THAI ORDER BY br.REGION_NAME_THAI

--SELECT BY province
SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, 
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE mdp.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
	SUM(CASE mdp.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
WHERE bp.PROVINCE_CODE = '40' 
GROUP BY bp.PROVINCE_CODE, bp.PROVINCE_NAME 

--select by amp
SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, bd.DISTRICT_CODE, bd.DISTRICT_NAME,
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE mdp.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
	SUM(CASE mdp.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_DISTRICT bd ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)  = CONCAT(bd.PROVINCE_CODE,bd.DISTRICT_CODE) 
--WHERE mda.PROVINCE_CODE = '40'
WHERE CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)='4025'
GROUP BY bp.PROVINCE_CODE, bp.PROVINCE_NAME ,bd.DISTRICT_CODE, bd.DISTRICT_NAME

--select by tam
SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, bd.DISTRICT_CODE, bd.DISTRICT_NAME, bs.SUBDISTRICT_CODE, bs.SUBDISTRICT_NAME, 
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE mdp.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
	SUM(CASE mdp.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_DISTRICT bd ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)  = CONCAT(bd.PROVINCE_CODE,bd.DISTRICT_CODE) 
LEFT JOIN "OPP$_DBA".BS_SUBDISTRICT bs ON CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 2))) = CONCAT(bs.PROVINCE_CODE, CONCAT(bs.DISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE , 2))) 
--WHERE mda.PROVINCE_CODE = '40'
WHERE CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 2))) = '4025100'
GROUP BY bp.PROVINCE_CODE, bp.PROVINCE_NAME ,bd.DISTRICT_CODE, bd.DISTRICT_NAME, bs.SUBDISTRICT_CODE, bs.SUBDISTRICT_NAME

--select age and TYPE by pro
WITH mdp AS (
	SELECT m.*, SUBSTR(m.BIRTH_DATE,-4)-543||'-'||SUBSTR(m.BIRTH_DATE,4,2)||'-'||SUBSTR(m.BIRTH_DATE,1,2) AS BDATE FROM "OPP$_DBA".MN_DES_PERSON m
)

SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, 
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE bd.DEFORM_ID WHEN '0' THEN 1 ELSE 0 END) AS type0, 
	SUM(CASE bd.DEFORM_ID WHEN '11' THEN 1 ELSE 0 END) AS type12,
	SUM(CASE bd.DEFORM_ID WHEN '12' THEN 1 ELSE 0 END) AS type13,
	SUM(CASE bd.DEFORM_ID WHEN '13' THEN 1 ELSE 0 END) AS type14,
	SUM(CASE bd.DEFORM_ID WHEN '14' THEN 1 ELSE 0 END) AS type15,
	SUM(CASE bd.DEFORM_ID WHEN '15' THEN 1 ELSE 0 END) AS type16,
	SUM(CASE bd.DEFORM_ID WHEN '16' THEN 1 ELSE 0 END) AS type17,
	SUM(CASE bd.DEFORM_ID WHEN '17' THEN 1 ELSE 0 END) AS type18
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID = mdd.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_DEFORM bd ON mdd.DEFORM_ID = bd.DEFORM_ID 
WHERE 
--bp.PROVINCE_CODE = '40' AND 
((SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-(SUBSTR(mdp.BIRTH_DATE,-4)-543)) < 50
GROUP BY bp.PROVINCE_CODE, bp.PROVINCE_NAME 

---select age and TYPE by amp
SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, bd.DISTRICT_CODE, bd.DISTRICT_NAME,
            COUNT(bp.PROVINCE_CODE) AS TOTAL,
            SUM(CASE bd.DEFORM_ID WHEN '0' THEN 1 ELSE 0 END) AS type0, 
            SUM(CASE bd.DEFORM_ID WHEN '11' THEN 1 ELSE 0 END) AS type12,
            SUM(CASE bd.DEFORM_ID WHEN '12' THEN 1 ELSE 0 END) AS type13,
            SUM(CASE bd.DEFORM_ID WHEN '13' THEN 1 ELSE 0 END) AS type14,
            SUM(CASE bd.DEFORM_ID WHEN '14' THEN 1 ELSE 0 END) AS type15,
            SUM(CASE bd.DEFORM_ID WHEN '15' THEN 1 ELSE 0 END) AS type16,
            SUM(CASE bd.DEFORM_ID WHEN '16' THEN 1 ELSE 0 END) AS type17,
            SUM(CASE bd.DEFORM_ID WHEN '17' THEN 1 ELSE 0 END) AS type18
        FROM "OPP$_DBA".MN_DES_PERSON mdp 
        LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
        LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
        LEFT JOIN "OPP$_DBA".BS_DISTRICT bd ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE) = CONCAT(bd.PROVINCE_CODE,bd.DISTRICT_CODE) 
        LEFT JOIN "OPP$_DBA".MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID = mdd.MAIMAD_ID 
        LEFT JOIN "OPP$_DBA".BS_DEFORM bd ON mdd.DEFORM_ID = bd.DEFORM_ID 
        WHERE mda.PROVINCE_CODE = '65' AND ((SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-(SUBSTR(mdp.BIRTH_DATE,-4)-543)) > 40 AND ((SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-(SUBSTR(mdp.BIRTH_DATE,-4)-543)) <= 50
        GROUP BY bp.PROVINCE_CODE, bp.PROVINCE_NAME, bd.DISTRICT_CODE, bd.DISTRICT_NAME
        
---select age and TYPE by edu
SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, 
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE bd.DEFORM_ID WHEN '0' THEN 1 ELSE 0 END) AS type0, 
	SUM(CASE bd.DEFORM_ID WHEN '11' THEN 1 ELSE 0 END) AS type12,
	SUM(CASE bd.DEFORM_ID WHEN '12' THEN 1 ELSE 0 END) AS type13,
	SUM(CASE bd.DEFORM_ID WHEN '13' THEN 1 ELSE 0 END) AS type14,
	SUM(CASE bd.DEFORM_ID WHEN '14' THEN 1 ELSE 0 END) AS type15,
	SUM(CASE bd.DEFORM_ID WHEN '15' THEN 1 ELSE 0 END) AS type16,
	SUM(CASE bd.DEFORM_ID WHEN '16' THEN 1 ELSE 0 END) AS type17,
	SUM(CASE bd.DEFORM_ID WHEN '17' THEN 1 ELSE 0 END) AS type18
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID = mdd.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_DEFORM bd ON mdd.DEFORM_ID = bd.DEFORM_ID 
WHERE 
--bp.PROVINCE_CODE = '40' AND 
((SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-(SUBSTR(mdp.BIRTH_DATE,-4)-543)) < 50
GROUP BY bp.PROVINCE_CODE, bp.PROVINCE_NAME         
        
        

SELECT vmdp.BDATE
--TO_DATE(CAST(vmdp.BDATE AS VARCHAR2(30)), 'YYYY-MM-DD') 
FROM "DEPGIS".V_MN_DES_PERSON vmdp 
WHERE SUBSTR(vmdp.BDATE, 6,2) = '00'

SELECT TRUNC((SYSDATE - TO_DATE(DOB, 'YYYY-MM-DD'))/ 365.25) AS AGE_TODAY FROM DUAL;

SELECT mdp.BIRTH_DATE,CONCAT() CONCAT(CONCAT(SUBSTR(mdp.BIRTH_DATE,4,2),'-'),SUBSTR(mdp.BIRTH_DATE,1,2)),  SUBSTR(mdp.BIRTH_DATE,-4)-543||'-'||SUBSTR(mdp.BIRTH_DATE,4,2)||'-'||SUBSTR(mdp.BIRTH_DATE,1,2)  AS bdate 
FROM MN_DES_PERSON mdp 
WHERE ()

SELECT TRUNC((SYSDATE - TO_DATE('1974-12-11', 'YYYY-MM-DD'))/365.25) AS AGE_TODAY FROM DUAL

--(SUBSTR(mdp.BIRTH_DATE,-4)-543||'-'||SUBSTR(mdp.BIRTH_DATE,4,2)||'-'||SUBSTR(mdp.BIRTH_DATE,1,2) )

-- create view boundary
CREATE VIEW "DEPGIS"."v_boundary" (
	TAM_CODE,
	TAM_NAME,
	AMP_CODE,
	AMP_NAME,
	PRO_CODE,
	PRO_NAME,
	REGION_CODE,
	REGION_NAME_THAI
) AS 
SELECT CONCAT(bs.PROVINCE_CODE,CONCAT(bs.DISTRICT_CODE,substr(bs.SUBDISTRICT_CODE,1,2))) AS TAM_CODE, 
	bs.SUBDISTRICT_NAME AS TAM_NAME, 
	CONCAT(bs.PROVINCE_CODE,bs.DISTRICT_CODE) AS AMP_CODE,
	--bs.*, 
	bd.DISTRICT_NAME AS AMP_NAME, 
	bs.PROVINCE_CODE AS PRO_CODE, 
	bp.PROVINCE_NAME AS PRO_NAME, 
	bp.REGION_CODE, 
	br.REGION_NAME_THAI
FROM BS_SUBDISTRICT bs 
LEFT JOIN BS_DISTRICT bd ON CONCAT(bs.PROVINCE_CODE,bs.DISTRICT_CODE) = CONCAT(bd.PROVINCE_CODE,bd.DISTRICT_CODE)
LEFT JOIN BS_PROVINCE bp ON bs.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN BS_REGION br ON bp.REGION_CODE = br.REGION_CODE 

-- create view data
CREATE VIEW dep_join_view AS  
SELECT mdp.*, mdah.*, mdd.*, bd.* 

CREATE VIEW "DEPGIS".aa AS 
SELECT mdp.*,
	mdah.ADDRESS_CODE,
	mdah.SEQ_NO,
	mdah.ADDRESS,
	mdah.MOO,
	mdah.SOI,
	mdah.STREET,
	mdah.SUB_DISTRICT,
	mdah.DISTRICT_CODE,
	mdah.PROVINCE_CODE,
	mdah.COUNTRY_CODE,
	mdah.POSTCODE,
	mdah.TELEPHONE,
	mdah.FAX,
	mdah.ADDRESS_NO,
	mdah.ADDRESS_ID,
	mdah.HIS_ID,
	mdd.DEFORM_ID,
	mdd.DEFORM_LEVEL,
	mdd.AGE,
	mdd.DEFORM_CAUSE_ID,
	mdd.DEF_DESC,
	mdd.DEFORM_SUB_NAME,
	mdd.TRANSFER_STATUS,
	mdd.AUTISTIC_STATUS,
	mdd.DEFORM_YEAR,
	mdd.DEFORM_MONTH,
	mdd.DIAGNOSE_STATUS,
	mdd.DEF_COMMENT,
	bd.FROM_TYPE_6_DOCTOR,
	bd.FORM_TYPE_8_STATUS,
	bd.FORM_TYPE_8_ALIAS,
	bd.FORM_COV_STATUS,
	bd.FORM_COV_ALIAS,
	bd.DEFORM_NAME,
	bd.STATUS,
	bd.CARD_STATUS,
	bd.CARD_STAFF_STATUS,
	bd.CARD_DOCTOR_STATUS,
	bd.DEFORM_ALIAS,
	bd.FORM_TYPE_6_STATUS,
	bd.FROM_TYPE_6_STAFF
FROM MN_DES_PERSON mdp
LEFT JOIN MN_DES_ADDRESS_HIS mdah ON mdp.MAIMAD_ID = mdah.MAIMAD_ID 
LEFT JOIN MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID =mdd.MAIMAD_ID 
LEFT JOIN BS_DEFORM bd  ON mdd.DEFORM_ID = bd.DEFORM_ID 

-- SET CLIENT_ENCODING TO UTF8;
-- SET STANDARD_CONFORMING_STRINGS TO ON;
-- BEGIN;
DROP TABLE "DEPGIS".th_amphoe_4326
CREATE TABLE "DEPGIS".th_amphoe_4326(
	gid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
	id numeric,
	ap_code varchar(4),
	ap_th varchar(60),
	ap_en varchar(50),
	pv_code varchar(2),
	pv_th varchar(50),
	pv_en varchar(50),
	re_nesdb varchar(50),
	re_royin varchar(50),
	areashape numeric,
	admin_type numeric,
	geom "MDSYS"."SDO_GEOMETRY"
);

CREATE TABLE "DEPGIS".th_amphoe_4326(geom "MDSYS"."SDO_GEOMETRY")

SELECT * FROM "DEPGIS".th_amphoe_4326
INSERT INTO "DEPGIS".th_amphoe_4326 values(sdo_geometry('POINT(121, 25)', 4326))

ALTER TABLE "DEPGIS"."th_amphoe_4326" ADD PRIMARY KEY (gid);
SELECT AddGeometryColumn('DEPGIS','th_amphoe_4326','geom','4326','MULTIPOLYGON',2);

/////// FROM join
DROP VIEW aaaa
CREATE VIEW "DEPGIS".aaaa2  AS SELECT bd.* FROM "OPP$_DBA".BS_DEFORM bd


CREATE VIEW "DEPGIS".V_MN_DES_PERSON AS 
SELECT m.*,  (SUBSTR(m.BIRTH_DATE,-4)-543||'-'||SUBSTR(m.BIRTH_DATE,4,2)||'-'||SUBSTR(m.BIRTH_DATE,1,2)) AS BDATE
FROM "OPP$_DBA".MN_DES_PERSON m

SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, bd.DISTRICT_CODE, bd.DISTRICT_NAME, bs.SUBDISTRICT_CODE, bs.SUBDISTRICT_NAME, 
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE mdp.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
	SUM(CASE mdp.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_DISTRICT bd ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)  = CONCAT(bd.PROVINCE_CODE,bd.DISTRICT_CODE) 
LEFT JOIN "OPP$_DBA".BS_SUBDISTRICT bs ON CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 2))) = CONCAT(bs.PROVINCE_CODE, CONCAT(bs.DISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE , 2))) 


SELECT bs.SUBDISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE, 1,2) FROM "OPP$_DBA".BS_SUBDISTRICT bs


SELECT * FROM "DEPGIS".MN_DES_PERSON

-- create 50%
CREATE TABLE "DEPGIS".MN_DES_PERSON AS SELECT * FROM "OPP$_DBA".MN_DES_PERSON mdp WHERE MOD(mdp.MAIMAD_ID, 2) <> 0;
CREATE TABLE "DEPGIS".MN_DES_ADDRESS AS SELECT * FROM "OPP$_DBA".MN_DES_ADDRESS mda WHERE MOD(mda.MAIMAD_ID, 2) <> 0;
CREATE TABLE "DEPGIS".WELFARE_620419_14_5 AS SELECT * FROM "OPP$_DBA".WELFARE_620419_14_5 w WHERE MOD(w."NO" , 2) <> 0;

 
-- CREATE V_MN_DES_PERSON
DROP TABLE "DEPGIS".V_MN_DES_PERSON

CREATE VIEW "DEPGIS".V_MN_DES_PERSON AS 
SELECT mdp.MAIMAD_ID,
			mdp.FIRST_NAME_THAI,
			mdp.LAST_NAME_THAI,
			mdp.PERSON_CODE,
			mdp.CARD_ID,
			mdp.SEX_CODE,
			mdp.BIRTH_DATE,
			mdp.DEATH_DATE,
			mdp.ISSUE_DATE,
			mdp.EXP_DATE,
			mdp.DEGREE_TYPE_CODE,
			mdp.OCCUPATION_CODE,
			mda.ADDRESS_CODE,
            mda.COUNTRY_CODE,
            --mda.ADDRESS_NO,
            mda.ADDRESS_ID,
            --mdd.DEFORM_ID,
           -- mdd.DEF_DESC,
           -- mdd.DEFORM_SUB_NAME,
            --bd.DEFORM_NAME,
            br.REGION_CODE,
            br.REGION_NAME_THAI,
            mda.PROVINCE_CODE,
            bp.PROVINCE_NAME,
            mda.DISTRICT_CODE,
            CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE) AS AMPCODE,
            bd2.DISTRICT_NAME,
            mda.SUB_DISTRICT,
            CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 1,2))) AS TAMCODE,
            bs.SUBDISTRICT_NAME, 
            (SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-(SUBSTR(mdp.BIRTH_DATE,-4)-543) AS AGE_NOW,
            (CASE WHEN LENGTH(mdp.OCCUPATION_CODE)=1 THEN CONCAT('00', mdp.OCCUPATION_CODE) ELSE (
				CASE WHEN LENGTH(mdp.OCCUPATION_CODE)=2 THEN CONCAT('0', mdp.OCCUPATION_CODE) ELSE (
					CASE WHEN mdp.OCCUPATION_CODE='99999' OR mdp.OCCUPATION_CODE IS NULL THEN '999' ELSE mdp.OCCUPATION_CODE 
					END) 
				END) 
			END ) AS OCC,
			w.NID,
			(CASE WHEN w.NID IS NOT NULL THEN '01' ELSE '02' END) AS privilege,
			TO_DATE(CONCAT(SUBSTR(mdp.issue_date, 4,2), SUBSTR(mdp.issue_date, 7,4) - 543), 'MMYYYY') AS NEWISSUE_DATE
FROM "DEPGIS".MN_DES_PERSON mdp
LEFT JOIN "DEPGIS".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "DEPGIS".WELFARE_620419_14_5 w ON mdp.CARD_ID = w.NID 
--LEFT JOIN "OPP$_DBA".MN_DES_CARD mdc ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
--LEFT JOIN "OPP$_DBA".MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID =mdd.MAIMAD_ID 
--LEFT JOIN "OPP$_DBA".BS_DEFORM bd  ON mdd.DEFORM_ID = bd.DEFORM_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_REGION br ON bp.REGION_CODE = br.REGION_CODE 
LEFT JOIN "OPP$_DBA".BS_DISTRICT bd2 ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)  = CONCAT(bd2.PROVINCE_CODE,bd2.DISTRICT_CODE) 
LEFT JOIN "OPP$_DBA".BS_SUBDISTRICT bs ON CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 1,2))) = CONCAT(bs.PROVINCE_CODE, CONCAT(bs.DISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE, 1,2))) 

WHERE SUBSTR(mdp.issue_date, 1,2)  >  '00' 
	AND SUBSTR(mdp.issue_date, 1,2)  <=  31
	AND SUBSTR(mdp.issue_date, 4,2)  >  '00' 
	AND SUBSTR(mdp.issue_date, 4,2)  <=  12
	AND SUBSTR(mdp.issue_date, 7,4)  >  2400
	
	AND mdp.DEATH_DATE IS NULL
	
/////	

SELECT * FROM DEPGIS.V_MN_DES_PERSON ORDER BY nid desc
GROUP BY PRIVILEGE 

SELECT mda.REGION_CODE, 
    mda.REGION_NAME_THAI,
    COUNT(mda.REGION_CODE) AS cnt,
    SUM(CASE mda.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
    SUM(CASE mda.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
    FROM "DEPGIS".V_MN_DES_PERSON mda
    WHERE mda.ADDRESS_CODE ='01' 
    GROUP BY mda.REGION_CODE, mda.REGION_NAME_THAI 
    ORDER BY mda.REGION_NAME_THAI


SELECT DISTINCT  mdp.OCCUPATION_CODE,
			(CASE WHEN LENGTH(mdp.OCCUPATION_CODE)=1 THEN CONCAT('00', mdp.OCCUPATION_CODE) ELSE (
				CASE WHEN LENGTH(mdp.OCCUPATION_CODE)=2 THEN CONCAT('0', mdp.OCCUPATION_CODE) ELSE (
					CASE WHEN mdp.OCCUPATION_CODE='99999' OR mdp.OCCUPATION_CODE IS NULL THEN '999' ELSE mdp.OCCUPATION_CODE 
					END) 
				END) 
			END ) AS OCC
		FROM  "DEPGIS".V_MN_DES_PERSON mdp

SELECT * FROM "OPP$_DBA".BS_DEGREE_TYPE
SELECT * FROM "OPP$_DBA".BS_DEGREE_TYPE_GROUP
SELECT * FROM "OPP$_DBA".BS_OCCUPATION

DROP VIEW "DEPGIS".v_get_by_region

CREATE VIEW "DEPGIS".v_get_by_region AS
SELECT mda.REGION_CODE, 
        mda.REGION_NAME_THAI,
        COUNT(mda.REGION_CODE) AS cnt,
        SUM(CASE mda.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
        SUM(CASE mda.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
    FROM "DEPGIS".V_MN_DES_PERSON mda
    --WHERE mda.ADDRESS_CODE ='${address_code}' 
    GROUP BY mda.REGION_CODE, mda.REGION_NAME_THAI 
    ORDER BY mda.REGION_NAME_THAI

DROP VIEW  "DEPGIS".MN_DES_ADDRESS    
CREATE TABLE "DEPGIS".MN_DES_ADDRESS AS

SELECT * FROM "DEPGIS".V_MN_DES_PERSON mda 

---------------เอาใหม่
SELECT ad.AGE AS CAT,
		SUM(CASE ad.OCC WHEN '001' THEN 1 ELSE 0 END) AS occ_001,
        SUM(CASE ad.OCC WHEN '002' THEN 1 ELSE 0 END) AS occ_002,
        SUM(CASE ad.OCC WHEN '003' THEN 1 ELSE 0 END) AS occ_003,
        SUM(CASE ad.OCC WHEN '004' THEN 1 ELSE 0 END) AS occ_004,
        SUM(CASE ad.OCC WHEN '005' THEN 1 ELSE 0 END) AS occ_005,
        SUM(CASE ad.OCC WHEN '006' THEN 1 ELSE 0 END) AS occ_006,
        SUM(CASE ad.OCC WHEN '007' THEN 1 ELSE 0 END) AS occ_007,
        SUM(CASE ad.OCC WHEN '008' THEN 1 ELSE 0 END) AS occ_008,
        SUM(CASE ad.OCC WHEN '009' THEN 1 ELSE 0 END) AS occ_009,
        SUM(CASE ad.OCC WHEN '010' THEN 1 ELSE 0 END) AS occ_010,
        SUM(CASE ad.OCC WHEN '011' THEN 1 ELSE 0 END) AS occ_011,
        SUM(CASE ad.OCC WHEN '012' THEN 1 ELSE 0 END) AS occ_012,
        SUM(CASE ad.OCC WHEN '013' THEN 1 ELSE 0 END) AS occ_013,
        SUM(CASE ad.OCC WHEN '014' THEN 1 ELSE 0 END) AS occ_014,
        SUM(CASE ad.OCC WHEN '015' THEN 1 ELSE 0 END) AS occ_015,
        SUM(CASE ad.OCC WHEN '016' THEN 1 ELSE 0 END) AS occ_016,
        SUM(CASE ad.OCC WHEN '017' THEN 1 ELSE 0 END) AS occ_017,
        SUM(CASE ad.OCC WHEN '018' THEN 1 ELSE 0 END) AS occ_018,
        SUM(CASE ad.OCC WHEN '019' THEN 1 ELSE 0 END) AS occ_019,
        SUM(CASE ad.OCC WHEN '020' THEN 1 ELSE 0 END) AS occ_020,
        SUM(CASE ad.OCC WHEN '999' THEN 1 ELSE 0 END) AS occ_999
FROM (SELECT mdp.REGION_NAME_THAI,
			CASE WHEN mdp.AGE_NOW  <= 5 THEN '1) <5' ELSE 
				CASE WHEN mdp.AGE_NOW  > 5 AND mdp.AGE_NOW  <= 14 THEN '2) 6-14' ELSE 
					CASE WHEN mdp.AGE_NOW  > 14 AND mdp.AGE_NOW  <= 21 THEN '3) 15-21' ELSE 
						CASE WHEN mdp.AGE_NOW  > 21 AND mdp.AGE_NOW  <= 59 THEN '4) 22-59' ELSE '5) >60' 
						END 
					END  
				END 
			END AS age,
			mdp.OCC
		FROM "DEPGIS".V_MN_DES_PERSON mdp 
		WHERE mdp.ADDRESS_CODE ='02' AND mdp.REGION_CODE IS NOT NULL) ad 
GROUP BY ad.AGE
ORDER BY ad.AGE


SELECT mdp.SUBDISTRICT_NAME  AS cat, 
        mdp.SUBDISTRICT_NAME,
        mdp.TAMCODE,
        SUM(CASE  WHEN mdp.SEX_CODE='M' OR mdp.SEX_CODE='F' OR mdp.SEX_CODE IS NULL  THEN 1 ELSE 0 END) AS cnt
    FROM "DEPGIS".V_MN_DES_PERSON mdp  
    WHERE mdp.ADDRESS_CODE ='01' AND mdp.DISTRICT_CODE='4603' --AND mdp.SUBDISTRICT_NAME IS NOT NULL
    GROUP BY mdp.SUBDISTRICT_NAME, mdp.TAMCODE 
    ORDER BY mdp.SUBDISTRICT_NAME

    
SELECT issue_date, SUBSTR(issue_date, 1,2), SUBSTR(issue_date, 4,2) FROM DEPGIS.V_MN_DES_PERSON 
WHERE SUBSTR(issue_date, 1,2)  <>  '00' OR SUBSTR(issue_date, 4,2)  <>  '00'
ORDER BY  issue_date ASC

SELECT TO_DATE(issue_date, 'dd-mm-yyyy')
FROM DEPGIS.V_MN_DES_PERSON 
WHERE SUBSTR(issue_date, 1,2)  <>  '00' OR SUBSTR(issue_date, 4,2)  <>  '00'

SELECT  ADD_MONTHS(to_date('29/02/2020'), 12 * 5 * -1) AS minus_5_year from dual

SELECT mdp.REGION_NAME_THAI AS cat, 
        mdp.REGION_NAME_THAI,
        mdp.REGION_CODE,
        SUM(CASE  WHEN mdp.SEX_CODE='M' OR mdp.SEX_CODE='F' OR mdp.SEX_CODE IS NULL  THEN 1 ELSE 0 END) AS cnt
    FROM "DEPGIS".V_MN_DES_PERSON mdp  
    WHERE mdp.ADDRESS_CODE ='${address_code}' ${pri} AND mdp.REGION_CODE IS NOT NULL
    GROUP BY mdp.REGION_NAME_THAI, mdp.REGION_CODE 
    ORDER BY mdp.REGION_NAME_THAI
 
WITH mdp(REGION_NAME_THAI,REGION_CODE,SEX_CODE,newd) AS (
	SELECT v.REGION_NAME_THAI, 
	v.REGION_CODE, 
	v.SEX_CODE, 
	--v.issue_date AS issue_date, 
	ADD_MONTHS(TO_DATE(v.issue_date, 'DD-MM-YYYY'), 12 * 543 * -1) AS newd
	FROM dual, DEPGIS.V_MN_DES_PERSON v
	WHERE v.ADDRESS_CODE ='02' AND v.REGION_CODE IS NOT NULL
	)
SELECT 
	mdp.REGION_NAME_THAI, mdp.REGION_CODE, 
	--mdp.REGION_NAME_THAI AS cat,
	---issue_date,mdp.newd,
	SUM(CASE  WHEN mdp.SEX_CODE='M' OR mdp.SEX_CODE='F' OR mdp.SEX_CODE IS NULL  THEN 1 ELSE 0 END) AS cnt
FROM mdp
WHERE mdp.newd >= TO_DATE('2019/04/23', 'YYYY/MM/DD') 
GROUP BY mdp.REGION_NAME_THAI, mdp.REGION_CODE 
ORDER BY mdp.REGION_NAME_THAI


SELECT  mdp.*,
	TO_DATE(CONCAT(SUBSTR(issue_date, 1,2), CONCAT(SUBSTR(issue_date, 4,2), SUBSTR(issue_date, 7,4) - 543)), 'DDMMYYYY') AS NEWISSUE_DATE
FROM dual, DEPGIS.V_MN_DES_PERSON mdp
WHERE mdp.ADDRESS_CODE ='02' AND mdp.REGION_CODE IS NOT NULL 
	AND SUBSTR(issue_date, 1,2)  >  '00' 
	AND SUBSTR(issue_date, 1,2)  <=  31
	AND SUBSTR(issue_date, 4,2)  >  '00' 
	AND SUBSTR(issue_date, 4,2)  <=  12
	AND SUBSTR(issue_date, 7,4)  >  2400
	AND TO_DATE(CONCAT(SUBSTR(issue_date, 4,2), SUBSTR(issue_date, 7,4) - 543), 'MMYYYY') > TO_DATE('10-2560', 'MM-YYYY')
	
	


////////////////////////
SELECT mdp.REGION_NAME_THAI AS cat, 
        mdp.REGION_NAME_THAI,
        mdp.REGION_CODE,
        SUM(CASE  WHEN mdp.SEX_CODE='M' OR mdp.SEX_CODE='F' OR mdp.SEX_CODE IS NULL  THEN 1 ELSE 0 END) AS cnt
    FROM "DEPGIS".V_MN_DES_PERSON mdp  
    WHERE mdp.ADDRESS_CODE ='02' AND (mdp.privilege ='01' OR mdp.privilege ='02') AND mdp.REGION_CODE IS NOT NULL
    	AND mdp.NEWISSUE_DATE > TO_DATE('01012020', 'DDMMYYYY')
    GROUP BY mdp.REGION_NAME_THAI, mdp.REGION_CODE 
    ORDER BY mdp.REGION_NAME_THAI
    
    
 SELECT * FROM "OPP$_DBA".BS_PROVINCE

 
 SELECT * FROM NEP_CARD.MN_CRD_REQUEST mcr 
 
 
SELECT 
sum(CASE WHEN DEATH_DATE IS NULL THEN 1 ELSE 0 END) AS total,
sum(CASE WHEN DEATH_DATE IS NOT NULL THEN 1 ELSE 0 END) AS totald,
sum(CASE WHEN SEX_CODE = 'F' AND DEATH_DATE IS NULL THEN 1 ELSE 0 END) AS f,
sum(CASE WHEN SEX_CODE = 'F' AND DEATH_DATE IS NOT NULL THEN 1 ELSE 0 END) AS fd,
sum(CASE WHEN SEX_CODE = 'M' AND DEATH_DATE IS NULL THEN 1 ELSE 0 END) AS m,
sum(CASE WHEN SEX_CODE = 'M' AND DEATH_DATE IS NOT NULL THEN 1 ELSE 0 END) AS md
FROM "DEPGIS".V_MN_DES_PERSON 
WHERE ADDRESS_CODE ='01'AND (privilege ='01' OR privilege ='02')
