DROP VIEW aaaa
CREATE VIEW "DEPGIS".aaaa2  AS SELECT bd.* FROM "OPP$_DBA".BS_DEFORM bd


CREATE VIEW "DEPGIS".V_MN_DES_PERSON AS 
SELECT m.*,  (SUBSTR(m.BIRTH_DATE,-4)-543||'-'||SUBSTR(m.BIRTH_DATE,4,2)||'-'||SUBSTR(m.BIRTH_DATE,1,2)) AS BDATE
FROM "OPP$_DBA".MN_DES_PERSON m

SELECT bp.PROVINCE_CODE, bp.PROVINCE_NAME, bd.DISTRICT_CODE, bd.DISTRICT_NAME, bs.SUBDISTRICT_CODE, bs.SUBDISTRICT_NAME, 
	COUNT(bp.PROVINCE_CODE) AS TOTAL,
	SUM(CASE mdp.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
	SUM(CASE mdp.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
FROM "OPP$_DBA".MN_DES_PERSON mdp 
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_DISTRICT bd ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)  = CONCAT(bd.PROVINCE_CODE,bd.DISTRICT_CODE) 
LEFT JOIN "OPP$_DBA".BS_SUBDISTRICT bs ON CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 2))) = CONCAT(bs.PROVINCE_CODE, CONCAT(bs.DISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE , 2))) 


SELECT bs.SUBDISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE, 1,2) FROM "OPP$_DBA".BS_SUBDISTRICT bs


GRANT CREATE VIEW TO depgis;

CREATE TABLE bb (gid numeric)

DROP VIEW "DEPGIS".V_MN_DES_PERSON

CREATE VIEW V_MN_DES_PERSON AS 
SELECT mdp.*,
	mda.ADDRESS_CODE,
          	mda.SEQ_NO,
            mda.ADDRESS,
            mda.MOO,
            mda.SOI,
            mda.STREET,
            mda.COUNTRY_CODE,
            mda.POSTCODE,
            mda.TELEPHONE,
            mda.FAX,
            mda.ADDRESS_NO,
            mda.ADDRESS_ID,
            mdd.DEFORM_ID,
            mdd.DEFORM_LEVEL,
            mdd.AGE,
            mdd.DEFORM_CAUSE_ID,
            mdd.DEF_DESC,
            mdd.DEFORM_SUB_NAME,
            mdd.TRANSFER_STATUS,
            mdd.AUTISTIC_STATUS,
            mdd.DEFORM_YEAR,
            mdd.DEFORM_MONTH,
            mdd.DIAGNOSE_STATUS,
            mdd.DEF_COMMENT,
            bd.FROM_TYPE_6_DOCTOR,
            bd.FORM_TYPE_8_STATUS,
            bd.FORM_TYPE_8_ALIAS,
            bd.FORM_COV_STATUS,
            bd.FORM_COV_ALIAS,
            bd.DEFORM_NAME,
            bd.STATUS,
            bd.CARD_STATUS,
            bd.CARD_STAFF_STATUS,
            bd.CARD_DOCTOR_STATUS,
            bd.DEFORM_ALIAS,
            bd.FORM_TYPE_6_STATUS,
            bd.FROM_TYPE_6_STAFF,
            br.REGION_CODE,
            br.REGION_NAME_THAI,
            mda.PROVINCE_CODE AS PROCODE,
            bp.PROVINCE_NAME,
            mda.DISTRICT_CODE,
            CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE) AS AMPCODE,
            bd2.DISTRICT_NAME,
            mda.SUB_DISTRICT,
            CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 1,2))) AS TAMCODE,
            bs.SUBDISTRICT_NAME, 
            (SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-(SUBSTR(mdp.BIRTH_DATE,-4)-543) AS AGE_NOW
-- SELECT (SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL) - (substr(mdp.BIRTH_DATE, -4)-543) AS now_age
FROM "OPP$_DBA".MN_DES_PERSON mdp
LEFT JOIN "OPP$_DBA".MN_DES_ADDRESS mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID =mdd.MAIMAD_ID 
LEFT JOIN "OPP$_DBA".BS_DEFORM bd  ON mdd.DEFORM_ID = bd.DEFORM_ID 
LEFT JOIN "OPP$_DBA".BS_PROVINCE bp ON mda.PROVINCE_CODE = bp.PROVINCE_CODE 
LEFT JOIN "OPP$_DBA".BS_REGION br ON bp.REGION_CODE = br.REGION_CODE 
LEFT JOIN "OPP$_DBA".BS_DISTRICT bd2 ON CONCAT(mda.PROVINCE_CODE,mda.DISTRICT_CODE)  = CONCAT(bd2.PROVINCE_CODE,bd2.DISTRICT_CODE) 
LEFT JOIN "OPP$_DBA".BS_SUBDISTRICT bs ON CONCAT(mda.PROVINCE_CODE, CONCAT(mda.DISTRICT_CODE, SUBSTR(mda.SUB_DISTRICT, 1,2))) = CONCAT(bs.PROVINCE_CODE, CONCAT(bs.DISTRICT_CODE, SUBSTR(bs.SUBDISTRICT_CODE, 1,2))) 
WHERE mda.SUB_DISTRICT IS NOT null

SELECT * FROM DEPGIS.V_MN_DES_PERSON

SELECT mda.REGION_CODE, 
    mda.REGION_NAME_THAI,
    COUNT(mda.REGION_CODE) AS cnt,
    SUM(CASE mda.SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS M,
    SUM(CASE mda.SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS F 
    FROM "DEPGIS".V_MN_DES_PERSON mda
    WHERE mda.ADDRESS_CODE ='01' 
    GROUP BY mda.REGION_CODE, mda.REGION_NAME_THAI 
    ORDER BY mda.REGION_NAME_THAI

